package ninerouter

import "strings"

// Code generated from 9router registry. Do not edit by hand.
// Regenerate: node tproxy/scripts/generate-ninerouter-presets.mjs

type Preset struct {
	ID, Type, Name, BaseURL, AuthType, Category, CredentialAuth, AuthHint, ApiKeyURL string
	AuthModes                                                                        []string
	SupportsQuota, NoAuth, HasOAuth                                                  bool
}

var Presets = map[string]Preset{
	"alicode":           {ID: "alicode", Type: "openai-compatible", Name: "Alibaba", BaseURL: "https://coding.dashscope.aliyuncs.com/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://bailian.console.aliyun.com/?apiKey=1", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"alicode-intl":      {ID: "alicode-intl", Type: "openai-compatible", Name: "Alibaba Intl", BaseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://modelstudio.console.alibabacloud.com/?apiKey=1", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"anthropic":         {ID: "anthropic", Type: "anthropic-compatible", Name: "Anthropic", BaseURL: "https://api.anthropic.com", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.anthropic.com/settings/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"antigravity":       {ID: "antigravity", Type: "antigravity", Name: "Antigravity", BaseURL: "", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"assemblyai":        {ID: "assemblyai", Type: "elevenlabs", Name: "AssemblyAI", BaseURL: "https://api.assemblyai.com/v1/audio/transcriptions", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.assemblyai.com/app/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"aws-polly":         {ID: "aws-polly", Type: "elevenlabs", Name: "AWS Polly", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://console.aws.amazon.com/iam/home#/security_credentials", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"azure":             {ID: "azure", Type: "openai-compatible", Name: "Azure OpenAI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"black-forest-labs": {ID: "black-forest-labs", Type: "image", Name: "Black Forest Labs", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://api.bfl.ai", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"blackbox":          {ID: "blackbox", Type: "openai-compatible", Name: "Blackbox AI", BaseURL: "https://api.blackbox.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://www.blackbox.ai/api-management", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"brave-search":      {ID: "brave-search", Type: "tavily", Name: "Brave Search", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://api-dashboard.search.brave.com/app/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"byteplus":          {ID: "byteplus", Type: "openai-compatible", Name: "BytePlus ModelArk", BaseURL: "https://ark.ap-southeast.bytepluses.com/api/coding/v3", AuthType: "api_key", Category: "freeTier", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"cartesia":          {ID: "cartesia", Type: "elevenlabs", Name: "Cartesia", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://play.cartesia.ai/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"cerebras":          {ID: "cerebras", Type: "openai-compatible", Name: "Cerebras", BaseURL: "https://api.cerebras.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://cloud.cerebras.ai/platform", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"chutes":            {ID: "chutes", Type: "openai-compatible", Name: "Chutes AI", BaseURL: "https://llm.chutes.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://chutes.ai/app/api", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"claude":            {ID: "claude", Type: "claude", Name: "Claude Code", BaseURL: "https://api.anthropic.com", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"cline":             {ID: "cline", Type: "cline", Name: "Cline", BaseURL: "https://api.cline.bot/api/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://app.cline.bot", AuthModes: []string{"oauth", "apikey"}, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"clinepass":         {ID: "clinepass", Type: "clinepass", Name: "ClinePass", BaseURL: "https://api.cline.bot/api/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://app.cline.bot", AuthModes: []string{"oauth", "apikey"}, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"cloudflare-ai":     {ID: "cloudflare-ai", Type: "openai-compatible", Name: "Cloudflare", BaseURL: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1", AuthType: "api_key", Category: "freeTier", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://dash.cloudflare.com/profile/api-tokens", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"codebuddy-cn":      {ID: "codebuddy-cn", Type: "codebuddy-cn", Name: "CodeBuddy CN", BaseURL: "https://copilot.tencent.com/v2", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://copilot.tencent.com", AuthModes: []string{"oauth", "apikey"}, SupportsQuota: true, NoAuth: false, HasOAuth: true},
	"codex":             {ID: "codex", Type: "codex", Name: "OpenAI Codex", BaseURL: "https://chatgpt.com/backend-api/codex", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"cohere":            {ID: "cohere", Type: "openai-compatible", Name: "Cohere", BaseURL: "https://api.cohere.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://dashboard.cohere.com/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"comfyui":           {ID: "comfyui", Type: "image", Name: "ComfyUI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"commandcode":       {ID: "commandcode", Type: "openai-compatible", Name: "Command Code", BaseURL: "https://api.commandcode.ai/alpha/generate", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://commandcode.ai/studio", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"coqui":             {ID: "coqui", Type: "elevenlabs", Name: "Coqui TTS", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"cursor":            {ID: "cursor", Type: "cursor", Name: "Cursor IDE", BaseURL: "https://api2.cursor.sh", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "Import access token from Cursor IDE (Settings → Account). Upstream routing uses Cursor Connect API.", ApiKeyURL: "https://cursor.com", AuthModes: []string{"oauth"}, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"deepgram":          {ID: "deepgram", Type: "elevenlabs", Name: "Deepgram", BaseURL: "https://api.deepgram.com/v1/listen", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://console.deepgram.com/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"deepseek":          {ID: "deepseek", Type: "openai-compatible", Name: "DeepSeek", BaseURL: "https://api.deepseek.com", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://platform.deepseek.com/api_keys", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"edge-tts":          {ID: "edge-tts", Type: "elevenlabs", Name: "Edge TTS", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"elevenlabs":        {ID: "elevenlabs", Type: "elevenlabs", Name: "ElevenLabs", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://elevenlabs.io/app/settings/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"exa":               {ID: "exa", Type: "tavily", Name: "Exa", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://dashboard.exa.ai/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"fal-ai":            {ID: "fal-ai", Type: "image", Name: "Fal.ai", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://fal.ai/dashboard/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"featherless":       {ID: "featherless", Type: "openai-compatible", Name: "Featherless", BaseURL: "https://api.featherless.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://featherless.ai/account/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"firecrawl":         {ID: "firecrawl", Type: "tavily", Name: "Firecrawl", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.firecrawl.dev/app/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"fireworks":         {ID: "fireworks", Type: "openai-compatible", Name: "Fireworks AI", BaseURL: "https://api.fireworks.ai/inference/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://fireworks.ai/account/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"gemini":            {ID: "gemini", Type: "gemini", Name: "Gemini", BaseURL: "https://generativelanguage.googleapis.com", AuthType: "api_key", Category: "freeTier", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://aistudio.google.com/app/apikey", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"gemini-cli":        {ID: "gemini-cli", Type: "antigravity", Name: "Gemini CLI", BaseURL: "https://cloudcode-pa.googleapis.com/v1internal", AuthType: "oauth", Category: "free", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"github":            {ID: "github", Type: "copilot", Name: "GitHub Copilot", BaseURL: "https://api.githubcopilot.com", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"gitlab":            {ID: "gitlab", Type: "gitlab", Name: "GitLab Duo", BaseURL: "https://gitlab.com/api/v4", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "Set gitlab_client_id in provider config", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"glm":               {ID: "glm", Type: "openai-compatible", Name: "GLM", BaseURL: "https://api.z.ai/api/paas/v4", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "General API (pay-as-you-go): keep this URL. GLM Coding Plan keys must use https://api.z.ai/api/coding/paas/v4 instead.", ApiKeyURL: "https://open.bigmodel.cn/usercenter/apikeys", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"glm-cn":            {ID: "glm-cn", Type: "openai-compatible", Name: "GLM (China)", BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://open.bigmodel.cn/usercenter/apikeys", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"google-pse":        {ID: "google-pse", Type: "tavily", Name: "Google PSE", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://programmablesearchengine.google.com/controlpanel/create", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"google-tts":        {ID: "google-tts", Type: "elevenlabs", Name: "Google TTS", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"grok-cli":          {ID: "grok-cli", Type: "xai", Name: "Grok CLI (Grok Build)", BaseURL: "https://cli-chat-proxy.grok.com/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: []string{"oauth"}, SupportsQuota: true, NoAuth: false, HasOAuth: true},
	"grok-web":          {ID: "grok-web", Type: "grok-web", Name: "Grok Web (Subscription)", BaseURL: "https://grok.com/rest/app-chat/conversations/new", AuthType: "api_key", Category: "webCookie", CredentialAuth: "cookie", AuthHint: "Paste your sso= cookie value from grok.com", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"groq":              {ID: "groq", Type: "openai-compatible", Name: "Groq", BaseURL: "https://api.groq.com/openai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://console.groq.com/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"huggingface":       {ID: "huggingface", Type: "openai-compatible", Name: "HuggingFace", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://huggingface.co/settings/tokens", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"hyperbolic":        {ID: "hyperbolic", Type: "openai-compatible", Name: "Hyperbolic", BaseURL: "https://api.hyperbolic.xyz/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://app.hyperbolic.xyz/settings", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"iflow":             {ID: "iflow", Type: "iflow", Name: "iFlow AI", BaseURL: "https://apis.iflow.cn/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"inworld":           {ID: "inworld", Type: "elevenlabs", Name: "Inworld TTS", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://platform.inworld.ai/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"jina-ai":           {ID: "jina-ai", Type: "openai-compatible", Name: "Jina AI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://jina.ai/?sui=apikey", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"jina-reader":       {ID: "jina-reader", Type: "tavily", Name: "Jina Reader", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://jina.ai/?sui=apikey", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"kilocode":          {ID: "kilocode", Type: "kilocode", Name: "Kilo Code", BaseURL: "https://api.kilo.ai/api/openrouter", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"kimchi":            {ID: "kimchi", Type: "kimchi", Name: "Kimchi", BaseURL: "https://llm.kimchi.dev/openai/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: []string{"oauth"}, SupportsQuota: false, NoAuth: false, HasOAuth: true},
	"kimi":              {ID: "kimi", Type: "kimi", Name: "Kimi", BaseURL: "https://api.kimi.com/coding/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://platform.moonshot.ai/console/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"kimi-coding":       {ID: "kimi-coding", Type: "kimi", Name: "Kimi Coding", BaseURL: "https://api.kimi.com/coding/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"kiro":              {ID: "kiro", Type: "kiro", Name: "Kiro AI", BaseURL: "https://runtime.us-east-1.kiro.dev/generateAssistantResponse", AuthType: "oauth", Category: "free", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: true},
	"linkup":            {ID: "linkup", Type: "tavily", Name: "Linkup", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://app.linkup.so/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"local-device":      {ID: "local-device", Type: "elevenlabs", Name: "Local Device", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"mimo-free":         {ID: "mimo-free", Type: "openai-compatible", Name: "MiMo Code Free", BaseURL: "https://api.xiaomimimo.com/api/free-ai/openai/chat", AuthType: "none", Category: "free", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"minimax":           {ID: "minimax", Type: "anthropic-compatible", Name: "Minimax Coding", BaseURL: "https://api.minimax.io/anthropic", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://platform.minimaxi.com/user-center/basic-information/interface-key", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"minimax-cn":        {ID: "minimax-cn", Type: "anthropic-compatible", Name: "Minimax (China)", BaseURL: "https://api.minimaxi.com/anthropic", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://platform.minimaxi.com/user-center/basic-information/interface-key", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"mistral":           {ID: "mistral", Type: "openai-compatible", Name: "Mistral", BaseURL: "https://api.mistral.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.mistral.ai/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"mmf":               {ID: "mmf", Type: "openai-compatible", Name: "MMF", BaseURL: "https://api.xiaomimimo.com/api/free-ai/openai/chat", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"nanobanana":        {ID: "nanobanana", Type: "image", Name: "NanoBanana API", BaseURL: "https://api.nanobananaapi.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://nanobananaapi.ai/dashboard", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"nebius":            {ID: "nebius", Type: "openai-compatible", Name: "Nebius AI", BaseURL: "https://api.studio.nebius.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://studio.nebius.com/settings/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"nvidia":            {ID: "nvidia", Type: "openai-compatible", Name: "NVIDIA NIM", BaseURL: "https://integrate.api.nvidia.com/v1", AuthType: "api_key", Category: "freeTier", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://build.nvidia.com/settings/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"ollama":            {ID: "ollama", Type: "ollama", Name: "Ollama Cloud", BaseURL: "https://ollama.com/api/chat", AuthType: "api_key", Category: "freeTier", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://ollama.com/settings/keys", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"ollama-local":      {ID: "ollama-local", Type: "ollama", Name: "Ollama Local", BaseURL: "http://localhost:11434/api/chat", AuthType: "none", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"openai":            {ID: "openai", Type: "openai-compatible", Name: "OpenAI", BaseURL: "https://api.openai.com/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://platform.openai.com/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"opencode":          {ID: "opencode", Type: "openai-compatible", Name: "OpenCode Free", BaseURL: "https://opencode.ai", AuthType: "none", Category: "free", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"opencode-go":       {ID: "opencode-go", Type: "openai-compatible", Name: "OpenCode Go", BaseURL: "https://opencode.ai/zen/go/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://opencode.ai/auth", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"openrouter":        {ID: "openrouter", Type: "openai-compatible", Name: "OpenRouter", BaseURL: "https://openrouter.ai/api/v1", AuthType: "api_key", Category: "freeTier", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://openrouter.ai/settings/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"perplexity":        {ID: "perplexity", Type: "openai-compatible", Name: "Perplexity", BaseURL: "https://api.perplexity.ai", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.perplexity.ai/settings/api", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"perplexity-agent":  {ID: "perplexity-agent", Type: "openai-compatible", Name: "Perplexity Agent", BaseURL: "https://api.perplexity.ai/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.perplexity.ai/settings/api", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"perplexity-web":    {ID: "perplexity-web", Type: "perplexity-web", Name: "Perplexity Web (Pro/Max)", BaseURL: "https://www.perplexity.ai/rest/sse/perplexity_ask", AuthType: "api_key", Category: "webCookie", CredentialAuth: "cookie", AuthHint: "Paste your __Secure-next-auth.session-token cookie value from perplexity.ai", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"playht":            {ID: "playht", Type: "elevenlabs", Name: "PlayHT", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://play.ht/studio/api-access", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"qoder":             {ID: "qoder", Type: "qoder", Name: "Qoder", BaseURL: "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation", AuthType: "oauth", Category: "free", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"qwen":              {ID: "qwen", Type: "qwen", Name: "Qwen Code", BaseURL: "https://portal.qwen.ai/v1", AuthType: "oauth", Category: "oauth", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"recraft":           {ID: "recraft", Type: "image", Name: "Recraft", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.recraft.ai/profile/api", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"runwayml":          {ID: "runwayml", Type: "image", Name: "Runway ML", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://dev.runwayml.com", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"sdwebui":           {ID: "sdwebui", Type: "image", Name: "SD WebUI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"searchapi":         {ID: "searchapi", Type: "tavily", Name: "SearchAPI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://www.searchapi.io/dashboard", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"searxng":           {ID: "searxng", Type: "tavily", Name: "SearXNG", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"serper":            {ID: "serper", Type: "tavily", Name: "Serper", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://serper.dev/api-key", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"siliconflow":       {ID: "siliconflow", Type: "openai-compatible", Name: "SiliconFlow", BaseURL: "https://api.siliconflow.com/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://cloud.siliconflow.com/account/ak", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"stability-ai":      {ID: "stability-ai", Type: "image", Name: "Stability AI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://platform.stability.ai/account/keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"tavily":            {ID: "tavily", Type: "tavily", Name: "Tavily", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://app.tavily.com/home", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"together":          {ID: "together", Type: "openai-compatible", Name: "Together AI", BaseURL: "https://api.together.xyz/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://api.together.xyz/settings/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"topaz":             {ID: "topaz", Type: "image", Name: "Topaz", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://topazlabs.com/account", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"tortoise":          {ID: "tortoise", Type: "elevenlabs", Name: "Tortoise TTS", BaseURL: "", AuthType: "none", Category: "freeTier", CredentialAuth: "none", AuthHint: "", ApiKeyURL: "", AuthModes: nil, SupportsQuota: false, NoAuth: true, HasOAuth: false},
	"venice":            {ID: "venice", Type: "openai-compatible", Name: "Venice AI", BaseURL: "https://api.venice.ai/api/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://venice.ai/settings/api", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"vercel-ai-gateway": {ID: "vercel-ai-gateway", Type: "openai-compatible", Name: "Vercel AI Gateway", BaseURL: "https://ai-gateway.vercel.sh/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://vercel.com/dashboard/~/ai-gateway", AuthModes: nil, SupportsQuota: true, NoAuth: false, HasOAuth: false},
	"vertex":            {ID: "vertex", Type: "vertex", Name: "Vertex AI", BaseURL: "https://aiplatform.googleapis.com", AuthType: "service_account", Category: "freeTier", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.cloud.google.com/iam-admin/serviceaccounts", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"vertex-partner":    {ID: "vertex-partner", Type: "vertex-partner", Name: "Vertex Partner", BaseURL: "https://aiplatform.googleapis.com", AuthType: "service_account", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.cloud.google.com/iam-admin/serviceaccounts", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"volcengine-ark":    {ID: "volcengine-ark", Type: "openai-compatible", Name: "Volcengine Ark", BaseURL: "https://ark.cn-beijing.volces.com/api/coding/v3", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"voyage-ai":         {ID: "voyage-ai", Type: "openai-compatible", Name: "Voyage AI", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://dash.voyageai.com/api-keys", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"xiaomi-mimo":       {ID: "xiaomi-mimo", Type: "openai-compatible", Name: "Xiaomi MiMo", BaseURL: "https://api.xiaomimimo.com/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://xiaomimimo.com", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"xiaomi-tokenplan":  {ID: "xiaomi-tokenplan", Type: "openai-compatible", Name: "Xiaomi MiMo (Token Plan)", BaseURL: "https://token-plan-sgp.xiaomimimo.com/v1", AuthType: "api_key", Category: "apikey", CredentialAuth: "", AuthHint: "", ApiKeyURL: "https://mimo.xiaomi.com", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
	"youcom":            {ID: "youcom", Type: "tavily", Name: "You.com Search", BaseURL: "", AuthType: "api_key", Category: "apikey", CredentialAuth: "apikey", AuthHint: "", ApiKeyURL: "https://api.you.com", AuthModes: nil, SupportsQuota: false, NoAuth: false, HasOAuth: false},
}

var Aliases = map[string]string{
	"aai":               "assemblyai",
	"ag":                "antigravity",
	"alicode":           "alicode",
	"alicode-intl":      "alicode-intl",
	"anthropic":         "anthropic",
	"ark":               "volcengine-ark",
	"assemblyai":        "assemblyai",
	"azure":             "azure",
	"bb":                "blackbox",
	"bfl":               "black-forest-labs",
	"black-forest-labs": "black-forest-labs",
	"blackbox":          "blackbox",
	"bpm":               "byteplus",
	"brave":             "brave-search",
	"byteplus":          "byteplus",
	"cartesia":          "cartesia",
	"cbcn":              "codebuddy-cn",
	"cc":                "claude",
	"cerebras":          "cerebras",
	"cf":                "cloudflare-ai",
	"ch":                "chutes",
	"chutes":            "chutes",
	"cl":                "cline",
	"clinepass":         "clinepass",
	"cloudflare-ai":     "cloudflare-ai",
	"cmc":               "commandcode",
	"cohere":            "cohere",
	"comfyui":           "comfyui",
	"commandcode":       "commandcode",
	"coqui":             "coqui",
	"cu":                "cursor",
	"cx":                "codex",
	"deepgram":          "deepgram",
	"deepseek":          "deepseek",
	"dg":                "deepgram",
	"ds":                "deepseek",
	"edge-tts":          "edge-tts",
	"el":                "elevenlabs",
	"exa":               "exa",
	"fal":               "fal-ai",
	"fal-ai":            "fal-ai",
	"featherless":       "featherless",
	"firecrawl":         "firecrawl",
	"fireworks":         "fireworks",
	"fl":                "featherless",
	"gb":                "grok-cli",
	"gc":                "gemini-cli",
	"gcli":              "grok-cli",
	"gemini":            "gemini",
	"gh":                "github",
	"glm":               "glm",
	"glm-cn":            "glm-cn",
	"google-tts":        "google-tts",
	"gpse":              "google-pse",
	"grok-build":        "grok-cli",
	"grok-web":          "grok-web",
	"groq":              "groq",
	"gw":                "grok-web",
	"hf":                "huggingface",
	"huggingface":       "huggingface",
	"hyp":               "hyperbolic",
	"hyperbolic":        "hyperbolic",
	"if":                "iflow",
	"inworld":           "inworld",
	"jina":              "jina-ai",
	"jina-reader":       "jina-reader",
	"kc":                "kilocode",
	"kimchi":            "kimchi",
	"kimi":              "kimi",
	"kmc":               "kimi-coding",
	"kr":                "kiro",
	"linkup":            "linkup",
	"local-device":      "local-device",
	"mimo":              "xiaomi-mimo",
	"minimax":           "minimax",
	"minimax-cn":        "minimax-cn",
	"mistral":           "mistral",
	"mmf":               "mimo-free",
	"nanobanana":        "nanobanana",
	"nb":                "nanobanana",
	"nebius":            "nebius",
	"nvidia":            "nvidia",
	"oc":                "opencode",
	"ocg":               "opencode-go",
	"ollama":            "ollama",
	"ollama-local":      "ollama-local",
	"openai":            "openai",
	"opencode-go":       "opencode-go",
	"openrouter":        "openrouter",
	"pa":                "perplexity-agent",
	"perplexity":        "perplexity",
	"perplexity-agent":  "perplexity-agent",
	"perplexity-web":    "perplexity-web",
	"playht":            "playht",
	"polly":             "aws-polly",
	"pplx":              "perplexity",
	"pplx-agent":        "perplexity-agent",
	"pplx-responses":    "perplexity-agent",
	"pw":                "perplexity-web",
	"qd":                "qoder",
	"qw":                "qwen",
	"recraft":           "recraft",
	"runway":            "runwayml",
	"runwayml":          "runwayml",
	"sdwebui":           "sdwebui",
	"searchapi":         "searchapi",
	"searxng":           "searxng",
	"serper":            "serper",
	"siliconflow":       "siliconflow",
	"stability":         "stability-ai",
	"stability-ai":      "stability-ai",
	"tavily":            "tavily",
	"together":          "together",
	"topaz":             "topaz",
	"tortoise":          "tortoise",
	"venice":            "venice",
	"vercel":            "vercel-ai-gateway",
	"vercel-ai-gateway": "vercel-ai-gateway",
	"vertex":            "vertex",
	"vertex-partner":    "vertex-partner",
	"vn":                "venice",
	"volcengine-ark":    "volcengine-ark",
	"voyage":            "voyage-ai",
	"voyage-ai":         "voyage-ai",
	"vx":                "vertex",
	"vxp":               "vertex-partner",
	"xai":               "xai",
	"xiaomi-mimo":       "xiaomi-mimo",
	"xiaomi-tokenplan":  "xiaomi-tokenplan",
	"xmtp":              "xiaomi-tokenplan",
	"youcom":            "youcom",
}

func Lookup(providerID string) (Preset, bool) {
	id := strings.TrimSpace(providerID)
	if id == "" {
		return Preset{}, false
	}
	if mapped, ok := Aliases[id]; ok {
		id = mapped
	}
	if preset, ok := Presets[id]; ok {
		return preset, true
	}
	preset, ok := Wave2Presets[id]
	return preset, ok
}
func ResolveProviderID(providerID string) string {
	if m, ok := Aliases[strings.TrimSpace(providerID)]; ok {
		return m
	}
	return strings.TrimSpace(providerID)
}
