package ninerouter

// Wave-2 provider presets (hand-maintained extensions; do not edit presets.go).
var Wave2Presets = map[string]Preset{
	"ai21":                {ID: "ai21", Type: "openai-compatible", Name: "AI21 Labs", BaseURL: "https://api.ai21.com/studio/v1", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://studio.ai21.com/account/api-keys"},
	"amazon-bedrock":      {ID: "amazon-bedrock", Type: "openai-compatible", Name: "Amazon Bedrock", BaseURL: "", AuthType: "api_key", Category: "apikey", AuthHint: "Use AWS access keys via IAM"},
	"anyscale":            {ID: "anyscale", Type: "openai-compatible", Name: "Anyscale Endpoints", BaseURL: "https://api.endpoints.anyscale.com/v1", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://console.anyscale.com/"},
	"baseten":             {ID: "baseten", Type: "openai-compatible", Name: "Baseten", BaseURL: "https://model-{modelId}.api.baseten.co/production/predict", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://app.baseten.co/settings/api-keys"},
	"cloudrift":           {ID: "cloudrift", Type: "openai-compatible", Name: "Cloudrift", BaseURL: "https://api.cloudrift.ai/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://cloudrift.ai"},
	"databricks":          {ID: "databricks", Type: "openai-compatible", Name: "Databricks Model Serving", BaseURL: "", AuthType: "api_key", Category: "apikey"},
	"deepinfra":           {ID: "deepinfra", Type: "openai-compatible", Name: "DeepInfra", BaseURL: "https://api.deepinfra.com/v1/openai", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://deepinfra.com/dash/api_keys"},
	"friendli":            {ID: "friendli", Type: "openai-compatible", Name: "FriendliAI", BaseURL: "https://api.friendli.ai/serverless/v1", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://friendli.ai"},
	"google-ai-studio":    {ID: "google-ai-studio", Type: "gemini", Name: "Google AI Studio", BaseURL: "https://generativelanguage.googleapis.com", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://aistudio.google.com/app/apikey"},
	"groq":                {ID: "groq", Type: "openai-compatible", Name: "Groq", BaseURL: "https://api.groq.com/openai/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://console.groq.com/keys"},
	"huggingface":         {ID: "huggingface", Type: "openai-compatible", Name: "Hugging Face Inference", BaseURL: "https://api-inference.huggingface.co/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://huggingface.co/settings/tokens"},
	"hyperbolic":          {ID: "hyperbolic", Type: "openai-compatible", Name: "Hyperbolic", BaseURL: "https://api.hyperbolic.xyz/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://hyperbolic.xyz"},
	"inception":           {ID: "inception", Type: "openai-compatible", Name: "Inception Labs", BaseURL: "https://api.inceptionlabs.ai/v1", AuthType: "api_key", Category: "apikey"},
	"lambda":              {ID: "lambda", Type: "openai-compatible", Name: "Lambda Labs", BaseURL: "https://api.lambdalabs.com/v1", AuthType: "api_key", Category: "apikey"},
	"lepton":              {ID: "lepton", Type: "openai-compatible", Name: "Lepton AI", BaseURL: "https://{workspace}.lepton.run/api/v1", AuthType: "api_key", Category: "apikey"},
	"lmstudio":            {ID: "lmstudio", Type: "openai-compatible", Name: "LM Studio", BaseURL: "http://localhost:1234/v1", AuthType: "none", Category: "freeTier", NoAuth: true},
	"mancer":              {ID: "mancer", Type: "openai-compatible", Name: "Mancer", BaseURL: "https://neuro.mancer.tech/v1", AuthType: "api_key", Category: "apikey"},
	"mistral":             {ID: "mistral", Type: "openai-compatible", Name: "Mistral AI", BaseURL: "https://api.mistral.ai/v1", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://console.mistral.ai/api-keys"},
	"modal":               {ID: "modal", Type: "openai-compatible", Name: "Modal", BaseURL: "", AuthType: "api_key", Category: "apikey"},
	"nebius":              {ID: "nebius", Type: "openai-compatible", Name: "Nebius Token Factory", BaseURL: "https://api.tokenfactory.nebius.com/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://tokenfactory.nebius.com"},
	"novita":              {ID: "novita", Type: "openai-compatible", Name: "Novita AI", BaseURL: "https://api.novita.ai/v3/openai", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://novita.ai"},
	"parasail":            {ID: "parasail", Type: "openai-compatible", Name: "Parasail", BaseURL: "https://api.parasail.io/v1", AuthType: "api_key", Category: "apikey"},
	"perplexity":          {ID: "perplexity", Type: "openai-compatible", Name: "Perplexity", BaseURL: "https://api.perplexity.ai", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://www.perplexity.ai/settings/api"},
	"replicate":           {ID: "replicate", Type: "openai-compatible", Name: "Replicate", BaseURL: "https://api.replicate.com/v1", AuthType: "api_key", Category: "apikey", ApiKeyURL: "https://replicate.com/account/api-tokens"},
	"sambanova":           {ID: "sambanova", Type: "openai-compatible", Name: "SambaNova", BaseURL: "https://api.sambanova.ai/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://cloud.sambanova.ai"},
	"scaleway":            {ID: "scaleway", Type: "openai-compatible", Name: "Scaleway Generative AI", BaseURL: "https://api.scaleway.ai/v1", AuthType: "api_key", Category: "apikey"},
	"siliconflow":         {ID: "siliconflow", Type: "openai-compatible", Name: "SiliconFlow", BaseURL: "https://api.siliconflow.cn/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://cloud.siliconflow.cn"},
	"together":            {ID: "together", Type: "openai-compatible", Name: "Together AI", BaseURL: "https://api.together.xyz/v1", AuthType: "api_key", Category: "freeTier", ApiKeyURL: "https://api.together.xyz/settings/api-keys"},
	"watsonx":             {ID: "watsonx", Type: "openai-compatible", Name: "IBM watsonx.ai", BaseURL: "", AuthType: "api_key", Category: "apikey"},
	"yuanbao":             {ID: "yuanbao", Type: "openai-compatible", Name: "Tencent Yuanbao", BaseURL: "https://api.yuanbao.tencent.com/v1", AuthType: "oauth", Category: "oauth", HasOAuth: true},
	"zed":                 {ID: "zed", Type: "openai-compatible", Name: "Zed AI", BaseURL: "https://api.zed.dev", AuthType: "oauth", Category: "oauth", HasOAuth: true},
}
